/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package olympics;

import connection.connection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoField;
import java.time.temporal.TemporalAccessor;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp-pc
 */
public class Check_transportation extends javax.swing.JFrame {
    
        Connection con = null;
        PreparedStatement p = null;
        ResultSet rs = null;
        String query;
        DefaultTableModel model;
       
        String source;
        String destination;
        String transportType;
        String arrTime;
        String depTime;
        

    /**
     * Creates new form Check_transportation
     */
            public void close(){
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
        
    }
    public Check_transportation() {
                 con = connection.connectDB();
                initComponents();
        model = (DefaultTableModel) transportTable.getModel();
        
        /////////////////
        for (int i = transportTable.getRowCount() - 1; i >= 0; i--) {
        model.removeRow(i);
        }
        /////////////////


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fromChoice = new javax.swing.JComboBox<>();
        toChoice = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        busCheck = new javax.swing.JCheckBox();
        trainCheck = new javax.swing.JCheckBox();
        search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        transportTable = new javax.swing.JTable();
        athleteSidebar5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        dashBoard1 = new javax.swing.JButton();
        transportInfo1 = new javax.swing.JButton();
        upcomingEvents1 = new javax.swing.JButton();
        scoreBoards1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        logout6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(252, 239, 186));

        jPanel2.setBackground(new java.awt.Color(252, 177, 49));

        fromChoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromChoice.setForeground(new java.awt.Color(130, 146, 149));
        fromChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "My Hostel", "SEC1", "SEC2", "SEC3", "SEC4", "SEC5", "SEC6" }));
        fromChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromChoiceActionPerformed(evt);
            }
        });

        toChoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toChoice.setForeground(new java.awt.Color(130, 146, 149));
        toChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "My Hostel", "SEC1", "SEC2", "SEC3", "SEC4", "SEC5", "SEC6" }));
        toChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toChoiceActionPerformed(evt);
            }
        });

        busCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        busCheck.setForeground(new java.awt.Color(255, 255, 255));
        busCheck.setSelected(true);
        busCheck.setText(" Bus");
        busCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busCheckActionPerformed(evt);
            }
        });

        trainCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trainCheck.setForeground(new java.awt.Color(255, 255, 255));
        trainCheck.setSelected(true);
        trainCheck.setText("Train");

        search.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        search.setText("Search");
        search.setActionCommand("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(busCheck)
                                .addGap(18, 18, 18)
                                .addComponent(trainCheck))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(toChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busCheck)
                    .addComponent(trainCheck))
                .addGap(27, 27, 27)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jButton4.setText("jButton4");

        header.setBackground(new java.awt.Color(130, 146, 149));

        jPanel30.setBackground(new java.awt.Color(255, 255, 240));

        jLabel20.setBackground(new java.awt.Color(255, 255, 240));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(193, 141, 107));
        jLabel20.setText("Transportation Details");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        transportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Source", "Destination", "Arrival Time", "Destination Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transportTable.setRowSelectionAllowed(false);
        table.setViewportView(transportTable);

        athleteSidebar5.setBackground(new java.awt.Color(252, 177, 49));

        jPanel11.setBackground(new java.awt.Color(255, 204, 153));

        jPanel27.setBackground(new java.awt.Color(255, 255, 240));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rings2(1).png"))); // NOI18N
        jLabel18.setToolTipText("");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("OLYMPICS");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel19)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 240));

        dashBoard1.setBackground(new java.awt.Color(130, 146, 149));
        dashBoard1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashBoard1.setForeground(new java.awt.Color(255, 255, 240));
        dashBoard1.setText("Dashboard");
        dashBoard1.setBorder(null);
        dashBoard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashBoard1ActionPerformed(evt);
            }
        });

        transportInfo1.setBackground(new java.awt.Color(130, 146, 152));
        transportInfo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transportInfo1.setForeground(new java.awt.Color(255, 255, 240));
        transportInfo1.setText("Transportation");
        transportInfo1.setBorder(null);
        transportInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportInfo1ActionPerformed(evt);
            }
        });

        upcomingEvents1.setBackground(new java.awt.Color(130, 146, 152));
        upcomingEvents1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        upcomingEvents1.setForeground(new java.awt.Color(255, 255, 240));
        upcomingEvents1.setText("Upcoming Events");
        upcomingEvents1.setBorder(null);
        upcomingEvents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcomingEvents1ActionPerformed(evt);
            }
        });

        scoreBoards1.setBackground(new java.awt.Color(130, 146, 152));
        scoreBoards1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        scoreBoards1.setForeground(new java.awt.Color(255, 255, 255));
        scoreBoards1.setText("Scoreboards");
        scoreBoards1.setBorder(null);
        scoreBoards1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBoards1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoreBoards1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upcomingEvents1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(dashBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(transportInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(upcomingEvents1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(scoreBoards1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("version 3.14");

        logout6.setBackground(new java.awt.Color(153, 153, 153));
        logout6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout6.setForeground(new java.awt.Color(255, 255, 255));
        logout6.setText("Logout");
        logout6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout athleteSidebar5Layout = new javax.swing.GroupLayout(athleteSidebar5);
        athleteSidebar5.setLayout(athleteSidebar5Layout);
        athleteSidebar5Layout.setHorizontalGroup(
            athleteSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, athleteSidebar5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(athleteSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1346, 1346, 1346))
            .addGroup(athleteSidebar5Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(athleteSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        athleteSidebar5Layout.setVerticalGroup(
            athleteSidebar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athleteSidebar5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(athleteSidebar5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1542, 1542, 1542)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(athleteSidebar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busCheckActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
            for (int i = transportTable.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);}        
////////////////////GET DATA//////////////////////////
        String str = dateChooser.getDate().toString();
        String[] arrOfStr = str.split(" ", 6);
        DateTimeFormatter parser = DateTimeFormatter.ofPattern("MMM").withLocale(Locale.ENGLISH);
        TemporalAccessor accessor = parser.parse(arrOfStr[1]);
        String month = Integer.toString(accessor.get(ChronoField.MONTH_OF_YEAR)) ; 
        String date = arrOfStr[2];
        String year = arrOfStr[5];
        

        
        boolean trainCheck = this.trainCheck.isSelected();
        boolean busCheck = this.busCheck.isSelected();
        String sourceInput = this.fromChoice.getSelectedItem().toString();
        String destinationInput = this.toChoice.getSelectedItem().toString();
       
        String tempStr;
        
       

        try {
 
            // SQL command data stored in String datatype
          //  query = String.format("select * from transportation where date = '%s-%s-%s'",year,month,date);
            if(!busCheck && !trainCheck)
            {
            query = " ";
            }
            else if(busCheck && trainCheck)
            query = String.format("select * from transportation where date = '%s-%s-%s'",year,month,date);
            else if(busCheck)
             query = String.format("select * from transportation where date = '%s-%s-%s' and type = 'Bus'",year,month,date);
            
            else if(trainCheck)
            query = String.format("select * from transportation where date = '%s-%s-%s' and type = 'Train'",year,month,date);
            
           if(!query.equals(""))
            {
                                String temp = String.format("select h.sector_id from athletes a, hostel h where a.athlete_id = (select currentUser from sys_properties where id = 1) and h.hostel_id = a.hostel_id;");
                p = con.prepareStatement(temp);      
                rs = p.executeQuery();
                rs.next();
                if(!fromChoice.getSelectedItem().toString().equals("Any"))
                {

                if(fromChoice.getSelectedItem().toString().equals("My Hostel"))
                {
                    query += String.format(" and source = '%s'",rs.getString("sector_id"));
                }
                else
                    query += String.format(" and source = '%s'",fromChoice.getSelectedItem().toString());
                }
                if(!toChoice.getSelectedItem().toString().equals("Any"))
                {
                if(toChoice.getSelectedItem().toString().equals("My Hostel"))
                {
                    query += String.format(" and destination = '%s'",rs.getString("sector_id"));
                }
                else
                    query += String.format(" and destination = '%s'",toChoice.getSelectedItem().toString());
                }
            }
           
            System.out.print(query);
           // query = String.format("select * from transportation where date = '%s-%s-%s' and source = '%s' and destination = '%s'",year,month,date,sourceInput,destinationInput);
            p = con.prepareStatement(query);      
            rs = p.executeQuery();

            
            while(rs.next())
            {
                
            arrTime = rs.getString("arrival_time");
            depTime = rs.getString("departure_time");
            source  = rs.getString("source");
            destination = rs.getString("destination");
            transportType = rs.getString("type");
                        
            model.addRow(new String[]{transportType,source,destination,arrTime,depTime});
            }


        }
        catch (SQLException e)
        {
        System.out.println(e);
        }
        
        System.out.println(query);
            
        

    }//GEN-LAST:event_searchActionPerformed

    private void fromChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromChoiceActionPerformed

    private void toChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toChoiceActionPerformed

    private void scoreBoards1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBoards1ActionPerformed
        close();
        new Scoreboard_Page().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_scoreBoards1ActionPerformed

    private void upcomingEvents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcomingEvents1ActionPerformed
        close();
        new UpcomingEvents_Page().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_upcomingEvents1ActionPerformed

    private void transportInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportInfo1ActionPerformed
        close();
        new Check_transportation().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_transportInfo1ActionPerformed

    private void dashBoard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashBoard1ActionPerformed
        close();
        new AthleteMain_Page().setVisible(true);
    }//GEN-LAST:event_dashBoard1ActionPerformed

    private void logout6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout6ActionPerformed
        close();
        new loginPage().setVisible(true);
    }//GEN-LAST:event_logout6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_transportation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_transportation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel athleteSidebar5;
    private javax.swing.JCheckBox busCheck;
    private javax.swing.JButton dashBoard1;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JComboBox<String> fromChoice;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton logout6;
    private javax.swing.JButton scoreBoards1;
    private javax.swing.JButton search;
    private javax.swing.JScrollPane table;
    private javax.swing.JComboBox<String> toChoice;
    private javax.swing.JCheckBox trainCheck;
    private javax.swing.JButton transportInfo1;
    private javax.swing.JTable transportTable;
    private javax.swing.JButton upcomingEvents1;
    // End of variables declaration//GEN-END:variables
}
